version: '3.8'

services:
  web:
    tty: true
    build: .
    container_name: osiris_back
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - elastic_net

networks:
  elastic_net:
    external: true