"""
Django settings for osiris project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
import logging
#from elasticsearch import Elasticsearch, exceptions as es_exceptions
from osiris.aws_ssm import get_ssm_parameter
from dotenv import load_dotenv
load_dotenv()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'elasticsearch': {   # logger específico para ES
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-a(yqs0u3bd_kb6u8%d$yqhu8xbxm$cr=#pkf3y^nr47kx^#nq6"

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.getenv("DEBUG", "False").lower() == "true"
DEBUG = "true"

#ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_yasg",
    'rest_framework',
    "corsheaders",
    'apps.observatorios',
    'apps.factores',
    "apps.caracteristicas",
    "apps.aspectos",
    "apps.estructuras",
    'apps.datos',
    'apps.campos',
    'apps.graficos'
]


CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = ["*"]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "osiris.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "osiris.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#HAYSTACK_URL_CONNECTION =  "" 
#HAYSTACK_ADMIN_INDEX = ".admin"
#HAYSTACK_CONNECTIONS = {
#    'default': {
#        'ENGINE': 'haystack.backends.elasticsearch7_backend.Elasticsearch7SearchEngine',
#        'URL': 'http://localhost:9200/',  # URL de tu servidor Elasticsearch
#        'INDEX_NAME': f'{HAYSTACK_ADMIN_INDEX}',      # Nombre del índice
#    },
#}



ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST")  
ELASTICSEARCH_PORT = os.getenv("ELASTICSEARCH_PORT") 
ELASTICSEARCH_MAIN_INDEX = os.getenv("ELASTICSEARCH_MAIN_INDEX") 

PARAMETER_STORE_BASE = os.getenv("PARAMETER_STORE")

base_path = f"/{PARAMETER_STORE_BASE}/observatorios_crud/db/"

ES_USERNAME = get_ssm_parameter(base_path + "username")
ES_PASSWORD = get_ssm_parameter(base_path + "password")

print("======================================")
print("✅ ELASTICSEARCH CONFIG")
print("PARAMETER_STORE_BASE:", PARAMETER_STORE_BASE)
print("BASE_PATH:", base_path)
print("======================================")

#ES_USERNAME = os.getenv("ELASTICSEARCH_USERNAME") 
#ES_PASSWORD = os.getenv("ELASTICSEARCH_PASSWORD")

#ELASTICSEARCH_DSL = {
#    'default': {
#        'HOST': ELASTICSEARCH_HOST,
#        'PORT': ELASTICSEARCH_PORT,
#    },
#}

ELASTICSEARCH_DSL = {
    'default': {
        'HOST': ELASTICSEARCH_HOST,
        'PORT': ELASTICSEARCH_PORT,
        'USERNAME': ES_USERNAME,
        'PASSWORD': ES_PASSWORD,
    },
}

#ES_HOST = f"{ELASTICSEARCH_DSL['default']['HOST']}:{ELASTICSEARCH_DSL['default']['PORT']}"
ES_HOST = f"http://{ELASTICSEARCH_DSL['default']['USERNAME']}:{ELASTICSEARCH_DSL['default']['PASSWORD']}@{ELASTICSEARCH_DSL['default']['HOST']}:{ELASTICSEARCH_DSL['default']['PORT']}"
print("======================================")
print("ES_HOST:", ES_HOST)
print("======================================")
# Log y prueba de conexión
#es_logger = logging.getLogger("elasticsearch")
#
#try:
#    es = Elasticsearch(ES_HOST)
#    if es.ping():
#        es_logger.info(f"✅ Elasticsearch conectado correctamente: {ES_HOST}")
#    else:
#        es_logger.error(f"⚠️ Elasticsearch no respondió al ping: {ES_HOST}")
#except es_exceptions.ConnectionError as e:
#    es_logger.error(f"❌ Error conectando a Elasticsearch: {e}")
#except Exception as e:
#    es_logger.error(f"❌ Error inesperado al conectar a Elasticsearch: {e}")
#
#SWAGGER_SETTINGS = {
#   'USE_SESSION_AUTH': False
#}

#HAYSTACK_URL_CONNECTION =  "" 
#HAYSTACK_ADMIN_INDEX = ".admin"
#HAYSTACK_CONNECTIONS = {
#    'default': {
#        'ENGINE': 'haystack.backends.elasticsearch7_backend.Elasticsearch7SearchEngine',
#        'URL': f"http://{ELASTICSEARCH_HOST}:{ELASTICSEARCH_PORT}",
#        'INDEX_NAME': f'{HAYSTACK_ADMIN_INDEX}',
#    },
#}

HAYSTACK_ADMIN_INDEX = ".admin"
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch7_backend.Elasticsearch7SearchEngine',
        'URL': f"http://{ES_USERNAME}:{ES_PASSWORD}@{ELASTICSEARCH_HOST}:{ELASTICSEARCH_PORT}",
       'INDEX_NAME': f'{HAYSTACK_ADMIN_INDEX}',
    },
}

LANGUAGE_CODE = 'es'

STATIC_URL = 'static/'
MEDIA_URL = '/media/'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# APPEND_SLASH=False


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,  # Número de elementos por página
}

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'apps.utils.views.custom_exception_handler'
}

GRAFICOS = ["pie", "barras", "linea", "multiple_linea" , "heatmap"]

